name: Python & Shell Script Test

on:
  push:
    branches:
      - main

    pull_request:
      types: [synchronize, review_requested]

jobs:
  python_test:
    name: Testing Python scripts with ver. 3.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Caching dependencies
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies # Download Python testing library flake8
        run: | 
          python -m pip install --upgrade pip
          pip install flake8 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  
  shellcheck:
    name: Test Shell script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error # Set minimum severity to error before it triggers test to fail
